version: 0.2

phases:
   install:
      runtime-versions:
         java: corretto17
   pre_build:
      commands:
         - echo Entered the pre_build phase...
         - mvn install
   build:
      commands:
         - echo Entered the build phase...
         - mvn clean package
      finally:
         - echo This always runs even if the install command fails
   post_build:
      commands:
         - echo Entered the post_build phase...

artifacts:
   files:
      - target/java-lambda-1.0-lambda-package.zip
      - appspec.yml
      - cloudformation.yml
   discard-paths: yes
cache:
   paths:
      - '/root/.m2/**/*'
