AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS Serverless Spring Boot 2 API - org.example::java-lambda
Globals:
  Api:
    EndpointConfiguration: REGIONAL

Resources:
  JavaLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      Code:
        S3Bucket: backend-package-bucket
        S3Key: backend-build/target/javaaws-0.0.1.jar
      Handler: org.example.StreamLambdaHandler::handleRequest
      Runtime: java17
      MemorySize: 512
      Policies: AWSLambdaBasicExecutionRole
      Timeout: 30
      Events:
        ProxyResource:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: any

Outputs:
  JavaLambdaApi:
    Description: URL for application
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/ping'
    Export:
      Name: JavaLambdaApi
